apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: name-project
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: name-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: name-project
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: name-project
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gimenesjhonathan/quarkus:latest
        imagePullPolicy: Always
        name: name-project