apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: client-api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: LoadBalancer