apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: client-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: client-api
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client-api
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gimenesjhonathan/oda-client-api
        imagePullPolicy: Always
        name: client-api